name: Sync Docs to Wiki

on:
  push:
    branches: [main]
    paths: [docs/**]

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki
      - run: |
          cp -r docs/* wiki/
          cd wiki
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Sync docs to wiki" || echo "No changes to commit"
          git push
